version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    BUILD_ARGS: ""
    DOCKERFILE_PATH: ""
    IMAGE_NAME: ""

phases:
  pre_build:
    commands:
      - set -e
      - echo "Build env:"
      - env
      - echo Logging in to Docker Hub...
      - echo "${DOCKERHUB_PASSWORD}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin public.ecr.aws
      - aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin "${PRIVATE_REGISTRY}"
  build:
    commands:
      - set -e
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build ${BUILD_ARGS} -t "${PUSH_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}${TAG_SUFFIX}" -f "${DOCKERFILE_PATH}" .
  post_build:
    commands:
      - set -e
      - echo Build completed on "$(date)"
      - docker --log-level=debug push "${PUSH_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}${TAG_SUFFIX}"
